# Use case configuration for the Unisoc UMS512/T618 DSP-mediated VBC path.
# Device(s): Anbernic RG Rotate (T618)

SectionDevice."Speaker" {
	Comment "Internal Speaker"

	EnableSequence [
		cset "name='VBC DAC0 AUD MDG Set' 1,1024"
	]

	DisableSequence [
		cset "name='VBC DAC0 AUD MDG Set' 0,1"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 1
	}
}
